services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./env/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
      - node_exporter
      - promtail
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - LOKI_STORAGE_PATH=/loki
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - ./logs:/var/log
      - ./env/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./env/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
    driver: local
