apiVersion: v1
kind: Service
metadata:
  name: springboot-prometheus-grafana-service
spec:
  selector:
    app: springboot-prometheus-grafana-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer