spring:
  application:
    name: springboot-prometheus-grafana
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

server:
  port: 8080
