server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.opentelemetry: DEBUG
    io.opentelemetry.api: DEBUG
    io.opentelemetry.sdk: DEBUG