global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'zhutao2014@163.com'
  smtp_auth_username: 'zhutao2014@163.com'
  smtp_auth_password: 'GSFYPHEZNWSBMXHH'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3m #重复问题，等待5分钟再告警一次
  receiver: 'web.hook'

  routes:
    - match:
        severity: 'critical'
      receiver: 'slack'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'zhangxuegang@gmail.com'
    webhook_configs:
      - url: 'http://localhost:8060/dingtalk/webhook/send'
        #inhibit_rules:
        #- source_match:
        # severity: 'critical'
        #target_match:
        # severity: 'warning'
        #equal: ['alertname', 'dev', 'instance']
