server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 102400
    batchwait: 5s

scrape_configs:
  # 收集系统日志
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          host: "{{ hostname }}"
          environment: production
          __path__: /var/log/*.log

  # 收集应用日志
  - job_name: application_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application_logs
          app: my_app
          environment: production
          __path__: /var/log/app/*.log

  # 收集微服务日志
  - job_name: microservices_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices_logs
          service: auth-service
          environment: staging
          __path__: /var/log/microservices/*.log
