scrape_configs:
  - job_name: 'springboot-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web:8080']
  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node_exporter:9100" ]